tap "homebrew/cask"
tap "homebrew/core"
brew "zsh"
brew "zsh-completions"
brew "direnv"
cask "iterm2"
cask "visual-studio-code"
brew "nvm"
brew "pyenv"
brew "tmux"
brew "fzf"
brew "watchman"                                 # Required for React Native
brew "cocoapods"                                # Xcode must be installed first. Required for React Native
