tap "caskroom/cask"
tap "homebrew/core"
tap alexandregz/MXhomebrew
cask "iterm2"
cask "java"
brew "yarn", args: ["without-node"]
brew "nvm"
brew "zsh"
brew "zsh-completions"
brew "tmux"
brew "bashmarks"
brew "fzf"
